# Generated by Django 6.0.5 on 2026-05-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={},
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='staff',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
